apiVersion: v1
kind: Config
clusters:
- name: my-cluster
  cluster:
    server: http://localhost:80
    certificate-authority-data: <base64-encoded-certificate>
users:
- name: my-user
  user:
    client-certificate-data: <base64-encoded-certificate>
    client-key-data: <base64-encoded-key>
contexts:
- name: my-context
  context:
    cluster: my-cluster
    user: my-user
    namespace: my-namespace
current-context: my-context
